version: '3.8'
services:
  api :
    build: ./backend
    ports:
     - 3000:3000
  
  db: 
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - todoapp:/app/data
volumes:
  todoapp: